-- simPython lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simPython=require('simPython')

function simPython.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simPython'][funcName]=wrapperGenerator(_G['simPython'][funcName])
    end

end

sim.registerScriptFuncHook('sysCall_init','simPython.__addTypeCheck',true)

return simPython
